# Generated by Django 4.1.3 on 2022-12-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='handle',
            field=models.CharField(db_index=True, default='@anon', max_length=14, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=14, verbose_name='name'),
        ),
    ]
