# Generated by Django 4.1.3 on 2022-12-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_handle_alter_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='likes'),
        ),
    ]
