# Generated by Django 4.1.3 on 2022-12-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='handle',
            field=models.CharField(db_index=True, default='@anon', max_length=14, verbose_name='handle'),
        ),
    ]
